spring.application.name=wallet

spring.datasource.url=jdbc:postgresql://postgres:5432/wallet
spring.datasource.username=wallet
spring.datasource.password=wallet

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}